# Generated by Django 4.2.30 on 2026-06-30 07:02

import crestpoint_credit.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillerCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Biller Category',
                'verbose_name_plural': 'Biller Categories',
                'db_table': 'biller_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=100)),
                ('biller_code', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billers', to='bills.billercategory')),
            ],
            options={
                'db_table': 'billers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('reference', models.CharField(default=crestpoint_credit.core.utils.generate_transaction_ref, editable=False, max_length=30, unique=True)),
                ('narration', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to='accounts.bankaccount')),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='bills.biller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bill_payments',
                'indexes': [models.Index(fields=['user', 'created_at'], name='ix_bp_user_created'), models.Index(fields=['status'], name='ix_bp_status')],
            },
        ),
        migrations.CreateModel(
            name='BillerSaved',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_by', to='bills.biller')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_billers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Biller',
                'verbose_name_plural': 'Saved Billers',
                'db_table': 'saved_billers',
                'unique_together': {('user', 'biller')},
            },
        ),
    ]
