# Generated by Django 4.2.30 on 2026-06-30 07:02

import crestpoint_credit.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckDeposit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('check_number', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('front_image', models.ImageField(upload_to='checks/')),
                ('back_image', models.ImageField(upload_to='checks/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('reference', models.CharField(default=crestpoint_credit.core.utils.generate_transaction_ref, editable=False, max_length=30, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_deposits', to='accounts.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'check_deposits',
                'indexes': [models.Index(fields=['user', 'status'], name='ix_cd_user_status'), models.Index(fields=['status'], name='ix_cd_status')],
            },
        ),
    ]
