# Generated by Django 4.2.30 on 2026-06-30 07:02

import crestpoint_credit.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_returns', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='investment_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment_accounts',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('change_percent', models.DecimalField(decimal_places=4, max_digits=8)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('average_buy_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pnl', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='investments.investmentaccount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='investments.stock')),
            ],
            options={
                'db_table': 'stock_holdings',
                'indexes': [models.Index(fields=['investment_account', 'stock'], name='ix_holding_account_stock')],
                'unique_together': {('investment_account', 'stock')},
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], db_index=True, default='completed', max_length=20)),
                ('reference', models.CharField(default=crestpoint_credit.core.utils.generate_transaction_ref, editable=False, max_length=30, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('investment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='investments.investmentaccount')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='investments.stock')),
            ],
            options={
                'db_table': 'investment_transactions',
                'indexes': [models.Index(fields=['investment_account', 'created_at'], name='ix_itx_account_created')],
            },
        ),
    ]
