# Generated by Django 4.2.30 on 2026-06-30 07:02

import crestpoint_credit.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wallet_address', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether')], default='BTC', max_length=10)),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='crypto_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crypto_wallets',
            },
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('swap', 'Swap')], db_index=True, max_length=20)),
                ('crypto_currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('usd_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=128)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='crypto/')),
                ('wallet_address', models.CharField(blank=True, default='', max_length=100)),
                ('reference', models.CharField(default=crestpoint_credit.core.utils.generate_transaction_ref, editable=False, max_length=30, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='crypto.cryptowallet')),
            ],
            options={
                'db_table': 'crypto_transactions',
                'indexes': [models.Index(fields=['wallet', 'created_at'], name='ix_ctx_wallet_created'), models.Index(fields=['status'], name='ix_ctx_status')],
            },
        ),
    ]
