# Generated by Django 6.0.6 on 2026-06-28 19:50

import crestpoint_credit.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(default=crestpoint_credit.payments.models.generate_payment_reference, editable=False, max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('debit_card', 'Debit Card'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money')], max_length=20)),
                ('provider', models.CharField(choices=[('stripe_mock', 'Stripe (Mock)'), ('paypal_mock', 'PayPal (Mock)'), ('bank_mock', 'Bank (Mock)')], default='bank_mock', max_length=20)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, default='', help_text='Unique identifier returned by the payment provider.', max_length=100)),
                ('provider_response', models.JSONField(blank=True, default=dict, help_text='Raw response payload from the payment provider.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary metadata attached to this payment.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Error details if the payment failed.')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Timestamp when the payment was completed or refunded.', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ix_payment_user_created'), models.Index(fields=['status'], name='ix_payment_status'), models.Index(fields=['reference'], name='ix_payment_reference')],
            },
        ),
    ]
