# Generated by Django 4.2.30 on 2026-06-30 07:02

import crestpoint_credit.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('cardholder_name', models.CharField(max_length=200)),
                ('expiry_month', models.CharField(max_length=2)),
                ('expiry_year', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=4)),
                ('card_type', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Physical')], default='virtual', max_length=20)),
                ('brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], default='visa', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('spending_limit', models.DecimalField(decimal_places=2, default=5000, max_digits=15)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed'), ('expired', 'Expired')], db_index=True, default='active', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_cards', to='accounts.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'virtual_cards',
            },
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('merchant_name', models.CharField(max_length=200)),
                ('merchant_category', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('reference', models.CharField(default=crestpoint_credit.core.utils.generate_transaction_ref, editable=False, max_length=30, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='cards.virtualcard')),
            ],
            options={
                'db_table': 'card_transactions',
            },
        ),
        migrations.CreateModel(
            name='CardFunding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('reference', models.CharField(default=crestpoint_credit.core.utils.generate_transaction_ref, editable=False, max_length=30, unique=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_fundings', to='accounts.bankaccount')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fundings', to='cards.virtualcard')),
            ],
            options={
                'db_table': 'card_fundings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='virtualcard',
            index=models.Index(fields=['user', 'status'], name='ix_vc_user_status'),
        ),
        migrations.AddIndex(
            model_name='cardtransaction',
            index=models.Index(fields=['card', 'created_at'], name='ix_ctx_card_created'),
        ),
    ]
