# Generated by Django 4.2.30 on 2026-06-29 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_withdrawalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalOTP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(editable=False, max_length=8)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_withdrawal_otps', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawal_otps',
                'ordering': ['-created_at'],
            },
        ),
    ]
